{% set version = "4.10.0" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-django/pytest_django-{{ version }}.tar.gz
  sha256: 1091b20ea1491fd04a310fc9aaff4c01b4e8450e3b157687625e16a6b5f3a366

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm >=1.11.1
  run:
    - python >={{ python_min }}
    - pytest >=5.4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
