{% set version = "4.8.0" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-django/pytest-django-{{ version }}.tar.gz
  sha256: 5d054fe011c56f3b10f978f41a8efb2e5adfc7e680ef36fb571ada1f24779d90

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.11.1
  run:
    - python >=3.6
    - pytest >=5.4.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
