{% set version = "4.9.0" %}

package:
  name: pytest-django
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-django/pytest_django-{{ version }}.tar.gz
  sha256: 8bf7bc358c9ae6f6fc51b6cebb190fe20212196e6807121f11bd6a3b03428314

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=1.11.1
  run:
    - python >={{ python_min }}
    - pytest >=5.4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pytest_django

about:
  home: http://pytest-django.readthedocs.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Django plugin for py.test
  doc_url: https://pytest-django.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-django

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
